In [1]:
import numpy as np

In [2]:
a=([1,2,3,4,5,6,7,8,9,10])
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
np.array(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
b=([[1,2,3],[4,5,6],[7,8,9]])
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
array_1=np.array(b)
array_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array_1.ndim

2

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.06996535, 0.39146068, 0.79005193, 0.30372116, 0.79180484])

In [24]:
array_2=np.random.randint(1,99,25)
array

array([73, 49, 42, 32, 91, 30,  1, 79, 60, 65, 84,  1, 53, 67, 27, 95, 16,
       80, 88,  9, 59, 79, 19, 88, 48])

In [25]:
array_2.reshape(5,5)

array([[63, 48, 89, 85,  2],
       [64, 67, 20, 50,  1],
       [35, 22, 95, 19, 34],
       [15,  6, 74,  4, 49],
       [96, 77, 20, 38, 38]])

In [26]:
array.max()

95

In [27]:
array.min()

1

In [28]:
array.argmax()

15

In [29]:
array.argmin()

6

In [30]:
array_3=array.reshape(5,5)
array_3

array([[73, 49, 42, 32, 91],
       [30,  1, 79, 60, 65],
       [84,  1, 53, 67, 27],
       [95, 16, 80, 88,  9],
       [59, 79, 19, 88, 48]])

In [31]:
array.shape

(25,)

In [32]:
np.empty(4)

array([9.10016856e+276, 1.38692357e+219, 7.87596779e+276, 1.76139229e+078])

In [34]:
array_4=np.arange(4,11)
array_4

array([ 4,  5,  6,  7,  8,  9, 10])

In [35]:
array_4[3]

7

In [36]:
array_4[:4]

array([4, 5, 6, 7])

In [37]:
array_4[2:]

array([ 6,  7,  8,  9, 10])

In [38]:
array_4[:]=6

In [39]:
array_4

array([6, 6, 6, 6, 6, 6, 6])

In [42]:
array_5=array_4.copy()
array_5

array([6, 6, 6, 6, 6, 6, 6])

In [44]:
array_3

array([[73, 49, 42, 32, 91],
       [30,  1, 79, 60, 65],
       [84,  1, 53, 67, 27],
       [95, 16, 80, 88,  9],
       [59, 79, 19, 88, 48]])

In [45]:
array_3[1,1]

1

In [46]:
array_3[0:2,0:2]

array([[73, 49],
       [30,  1]])

In [47]:
array_6=np.arange(10)
array_6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array_6>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [50]:
array_6[array_6>5]

array([6, 7, 8, 9])

In [51]:
array_6+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
np.sum(array_6)

45

In [53]:
array_6*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
np.prod(array_6)

0

In [55]:
array_6/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [56]:
array_6**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [57]:
np.sqrt(array_6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [58]:
np.var(array_6)

8.25

In [59]:
x=[1,2,3]
y=[4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [60]:
np.dot(x,y)

32

In [63]:
array_3

array([[73, 49, 42, 32, 91],
       [30,  1, 79, 60, 65],
       [84,  1, 53, 67, 27],
       [95, 16, 80, 88,  9],
       [59, 79, 19, 88, 48]])

In [64]:
np.transpose(array_3)

array([[73, 30, 84, 95, 59],
       [49,  1,  1, 16, 79],
       [42, 79, 53, 80, 19],
       [32, 60, 67, 88, 88],
       [91, 65, 27,  9, 48]])

In [65]:
f=[[1,2,3],[4,5,6]]
np.mean(f)

3.5

In [66]:
np.std(f)

1.707825127659933

In [67]:
np.cov(f)

array([[1., 1.],
       [1., 1.]])